### ISSUE TITLE
Angular2 minimal-nodetemplate

### ISSUE THREAD

**Issue by koppor** [lharzenetter/winery#14]
Angular2 app, die beim Start zwei Minimal-Nodetemplate runde Ecken hat und den Namen anzeigt.

Nodetemplate-DAten sind hard-coded, keine Verbindung zum Backend

- [x]  Komponente nodetemplate
- [x] Hauptseite bindet zwei Komponenten ein

<a href="https://timer.scm.io/repos/58594836b90300183507c996/issues/14/create?referer=github" target="_blank">Log Time</a>

**Comment by kepplene** [comment]
angular project can be found on
 repository: enpro-winery-internal
 branch: minimal-nodetemplate
 folder: Angular2_minimal-nodetemplate

**Comment by lharzenetter** [comment]
updated folder structure to match best practices as shown [here](https://scotch.io/tutorials/angularjs-best-practices-directory-structure) or [here in more details](https://docs.google.com/document/d/1XXMvReO8-Awi1EZXAXS4PzDzdNvV6pGcuaF4Q9821Es/pub)

also updated typescript dependency to be up to date.

**Comment by lharzenetter** [comment]
In my opinion it's okay! Moving the issue to colsed.
