### ISSUE TITLE
Setup intial CI infrastructure

### ISSUE THREAD

**Issue by koppor** [lharzenetter/winery#15]
- [x] Codacy
- [x] Codecov

See https://github.com/JabRef/jabref/ for an example

<a href="https://timer.scm.io/repos/58594836b90300183507c996/issues/15/create?referer=github" target="_blank">Log Time</a>

**Comment by nstadelmaier-dev** [comment]
codacy and codecov integration is implemented on branch: "codecov"

**Comment by koppor** [comment]
Currently, Eclipse Winery [complains that no coverage is found](https://travis-ci.org/eclipse/winery#L3695):

```
==> Travis CI detected.

    project root: .

    Yaml not found, that's ok! Learn more at http://docs.codecov.io/docs/codecov-yaml

==> Running gcov in . (disable via -X gcov)

==> Python coveragepy not found

==> Searching for coverage reports in:

    + .

--> No coverage report found.

    Please visit http://docs.codecov.io/docs/supported-languages
```

Did the codecov configuration go mad?
