### ISSUE TITLE
Setup infrastructure for time management

### ISSUE THREAD

**Issue by koppor** [lharzenetter/winery#16]
There is OSS software out there to enable tracking of times spent on GitHub issues.

- [x] Search for software
- [ ] Setup VM
- [x] Install software

<a href="https://timer.scm.io/repos/58594836b90300183507c996/issues/16/create?referer=github" target="_blank">Log Time</a>

**Comment by lharzenetter** [comment]
How about
- [ ] [GitHub-Time-tracking](https://github.com/StephenOTT/GitHub-Time-Tracking)
