### ISSUE TITLE
Angular2 skeletton for topology modeler

### ISSUE THREAD

**Issue by koppor** [lharzenetter/winery#9]
Provide a skeletton for the topology modeler

- [x] Show heading
- [x] Provide a component for the palette without content
  - [x] expandable on click

![grabbed_20161219-093253](https://cloud.githubusercontent.com/assets/1366654/21305827/1ed2a4a2-c5ce-11e6-9d5a-d1f30ef850d7.png)

<a href="https://timer.scm.io/repos/58594836b90300183507c996/issues/9/create?referer=github" target="_blank">Log Time</a>

**Comment by nstadelmaier-dev** [comment]
remove jQuery code from components
refactor DOM events to be Angular2 conform

**Comment by lharzenetter** [comment]
@nstadelmaier-dev, I removed the jQuery parts. Please check whether it's okay now.

**Comment by nstadelmaier-dev** [comment]
@lharzenetter The jQuery calls have been removed and events where changed to fit Angular2. The code looks fine now and the issue can be closed.
